package com.sysquare.ims.model.domain;
// Generated 28 Aug, 2012 9:23:52 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name="author"
    ,catalog="ims"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Author  implements java.io.Serializable {


     private Integer authorId;
     private String name;
     private String description;
     private boolean isActive;
     private Set<Paper> papers = new HashSet<Paper>(0);
     private Set<Note> notes = new HashSet<Note>(0);

    public Author() {
    }

	
    public Author(String name, boolean isActive) {
        this.name = name;
        this.isActive = isActive;
    }
    public Author(String name, String description, boolean isActive, Set<Paper> papers, Set<Note> notes) {
       this.name = name;
       this.description = description;
       this.isActive = isActive;
       this.papers = papers;
       this.notes = notes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="author_id", unique=true, nullable=false)
    public Integer getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
    
    @Column(name="name", unique=true, nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="is_active", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="author")
    public Set<Paper> getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set<Paper> papers) {
        this.papers = papers;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="author")
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }




}


