package com.sysquare.ims.model.domain;
// Generated 28 Aug, 2012 9:23:52 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="ims"
    , uniqueConstraints = @UniqueConstraint(columnNames="title") 
)
public class Course  implements java.io.Serializable {


     private Integer courseId;
     private String title;
     private String description;
     private Date createDate;
     private Date lastModifiedDate;
     private boolean isActive;
     private Set<CourseSubject> courseSubjects = new HashSet<CourseSubject>(0);

    public Course() {
    }

	
    public Course(Date lastModifiedDate, boolean isActive) {
        this.lastModifiedDate = lastModifiedDate;
        this.isActive = isActive;
    }
    public Course(String title, String description, Date createDate, Date lastModifiedDate, boolean isActive, Set<CourseSubject> courseSubjects) {
       this.title = title;
       this.description = description;
       this.createDate = createDate;
       this.lastModifiedDate = lastModifiedDate;
       this.isActive = isActive;
       this.courseSubjects = courseSubjects;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="course_id", unique=true, nullable=false)
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    
    @Column(name="title", unique=true, length=64)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified_date", nullable=false, length=19)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    
    @Column(name="is_active", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="course")
    public Set<CourseSubject> getCourseSubjects() {
        return this.courseSubjects;
    }
    
    public void setCourseSubjects(Set<CourseSubject> courseSubjects) {
        this.courseSubjects = courseSubjects;
    }




}


