package com.sysquare.ims.model.domain;
// Generated 28 Aug, 2012 9:23:52 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paper generated by hbm2java
 */
@Entity
@Table(name="paper"
    ,catalog="ims"
)
public class Paper  implements java.io.Serializable {


     private Integer paperId;
     private CourseSubject courseSubject;
     private Author author;
     private User user;
     private int severityId;
     private String title;
     private String fileName;
     private String filePath;
     private Date createDate;
     private Date lastModifiedDate;
     private boolean isActive;

    public Paper() {
    }

	
    public Paper(CourseSubject courseSubject, Author author, User user, int severityId, Date lastModifiedDate, boolean isActive) {
        this.courseSubject = courseSubject;
        this.author = author;
        this.user = user;
        this.severityId = severityId;
        this.lastModifiedDate = lastModifiedDate;
        this.isActive = isActive;
    }
    public Paper(CourseSubject courseSubject, Author author, User user, int severityId, String title, String fileName, String filePath, Date createDate, Date lastModifiedDate, boolean isActive) {
       this.courseSubject = courseSubject;
       this.author = author;
       this.user = user;
       this.severityId = severityId;
       this.title = title;
       this.fileName = fileName;
       this.filePath = filePath;
       this.createDate = createDate;
       this.lastModifiedDate = lastModifiedDate;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="paper_id", unique=true, nullable=false)
    public Integer getPaperId() {
        return this.paperId;
    }
    
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_subject_id", nullable=false)
    public CourseSubject getCourseSubject() {
        return this.courseSubject;
    }
    
    public void setCourseSubject(CourseSubject courseSubject) {
        this.courseSubject = courseSubject;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="author_id", nullable=false)
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="updated_by", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    @Column(name="severity_id", nullable=false)
    public int getSeverityId() {
        return this.severityId;
    }
    
    public void setSeverityId(int severityId) {
        this.severityId = severityId;
    }
    
    @Column(name="title", length=64)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="file_name", length=64)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="file_path", length=1024)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified_date", nullable=false, length=19)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    
    @Column(name="is_active", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


