package com.sysquare.ims.model.domain;

// Generated 30 Sep, 2012 3:42:28 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Severity generated by hbm2java
 */
@Entity
@Table(name = "severity", catalog = "ims", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Severity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer severityId;
	private String name;
	private boolean isActive;
	private Set<Paper> papers = new HashSet<Paper>(0);
	private User updatedBy;

	public Severity() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "severity_id", unique = true, nullable = false)
	public Integer getSeverityId() {
		return this.severityId;
	}

	public void setSeverityId(Integer severityId) {
		this.severityId = severityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updated_by", nullable = false)
	public User getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "name", unique = true, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "severity")
	public Set<Paper> getPapers() {
		return this.papers;
	}

	public void setPapers(Set<Paper> papers) {
		this.papers = papers;
	}

}
