package com.sysquare.ims.model.domain;

// Generated 30 Sep, 2012 3:42:28 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentSmsLog generated by hbm2java
 */
@Entity
@Table(name = "student_sms_log", catalog = "ims")
public class StudentSmsLog implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer studentSmsLogId;
	private Student student;
	private User sentBy;
	private Date sentDateTime;
	private String status;
	private String errorMsg;
	private boolean isActive;

	public StudentSmsLog() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "student_sms_log_id", unique = true, nullable = false)
	public Integer getStudentSmsLogId() {
		return this.studentSmsLogId;
	}

	public void setStudentSmsLogId(Integer studentSmsLogId) {
		this.studentSmsLogId = studentSmsLogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sent_by", nullable = false)
	public User getSentBy() {
		return this.sentBy;
	}

	public void setSentBy(User sentBy) {
		this.sentBy = sentBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sent_date_time", nullable = false, length = 19)
	public Date getSentDateTime() {
		return this.sentDateTime;
	}

	public void setSentDateTime(Date sentDateTime) {
		this.sentDateTime = sentDateTime;
	}

	@Column(name = "status", nullable = false, length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "error_msg", length = 65535)
	public String getErrorMsg() {
		return this.errorMsg;
	}

	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}

	@Column(name = "is_active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
